[WIP][feat]: Invite team member to the organization
fenske/devskills-app pull request #225
Opened 2021-06-06 21:53 UTC by Safi-Ullah

2021-06-06 21:55 UTC, Safi-Ullah commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Currently, the github invite to user is not being sent with the error `You must be an admin to create an invitation to an organization`
![Uploading Screenshot 2021-06-07 at 2.30.55 AM.png…]()

2021-06-06 21:59 UTC, Safi-Ullah commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
And, I just noticed that `username=undefined` is being passed but that still shouldn't be the cause since the invite is being sent via github email.

2021-06-07 08:39 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Should be fixed now. I forgot I created a new GitHub account called "DevSkills Robot - Dev" to separate it from the production service account. Made it Owner now so you won't see this problem anymore.

Also, the reason you got `username=undefined` was that you were already logged in on localhost (in that case GitHub doesn't return the username when logging in via Firebase Auth for some reason). For all newly invited users, they'll have to sign in which will make GitHub return the username correctly.

Also did some functional testing and let me share a few findings.

1. Now that the aforementioned invite problem is solved, it's now throwing another one when you follow the org invite link.
<img width="1723" alt="CleanShot 2021-06-07 at 10 36 54@2x" src="https://user-images.githubusercontent.com/1162212/120985978-6d62dd80-c77c-11eb-9a69-39ad92445eab.png">
<img width="1326" alt="CleanShot 2021-06-07 at 10 36 35@2x" src="https://user-images.githubusercontent.com/1162212/120986011-72279180-c77c-11eb-867d-1759a2d5a43d.png">

2. I can still invite users if I’m an admin on Individual or even if the org doesn’t have the “plan” property. Should comply with the following AC instead:
![CleanShot 2021-06-07 at 10 23 05@2x](https://user-images.githubusercontent.com/1162212/120984579-16103d80-c77b-11eb-87a9-fab521db8200.png)
3. There shouldn’t be a redirect to candidates after you’ve invited someone. It should remain on the same screen and the newly invited "pending" user should be added to the list right after.

2021-06-07 09:33 UTC, Safi-Ullah commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
One question, I can expect the `plan` property to already be set in the organization, right..?

2021-06-07 09:34 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
I'd say, if it's not set, then you only don't render the team settings (for backward compatibility).

2021-06-07 17:40 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
@Safi-Ullah Saw you pushed a change that says it fixes this comment but I'm still seeing error no. 1 when following an invite link. (you should be able to reproduce it too, just follow a link for an org invite)

Also, the newly invited member doesn't appear on the list right after clicking "Add", only after a refresh.


https://user-images.githubusercontent.com/1162212/121064634-1f73c700-c7c8-11eb-8618-60ae56d99c55.mp4

2021-06-07 19:14 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Just gave you write access on DevSkills Preview so that you can edit the Firestore there.

2021-06-07 19:15 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
> Also, can you give me an admin role for this vercel-app-deployment

Unfortunately, I think it's not that simple. 😬 Let me check.

2021-06-07 19:16 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
So that we're on the same page, you mean you want to be able to trigger deployments to a preview env by yourself, right?

2021-06-07 19:18 UTC, Safi-Ullah commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Actually, I was talking about setting the new custom claim `role=admin` for my user.

2021-06-07 19:19 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Should be fine now (ie. when you push an update, it'll deploy automatically)

2021-06-07 19:23 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
> Actually, I was talking about setting the new custom claim role=admin for my user as I couldn't access Team Members setting before.

Got it. One min.

2021-06-07 19:32 UTC, fenske commented on pages/api/organizations/invites/[id].tsx
> +    await inviteUserToGitHubOrg(orgGitHubId, githubEmail);
Done. Re-log in at https://app-coreskills-git-fork-safi-ullah-safi-invite-members-f-3e48d9.vercel.app/sign-in.

2021-06-08 11:15 UTC, fenske commented on pages/organizations/invites/[id].tsx
> +      window.location.href = '/organizations/invite-activated';
@Safi-Ullah Just an FYI I took the liberty to change this redirect as redirecting to "/candidates" would cause a confusing behavior.

For custom claims to be fetched the user either must re-login or wait until their session token rotates.

That's why we need to ask them to re-login explicitly (plus accept their GitHub invite), which is what we need the new `/invite-activated` page for.

2021-06-08 11:28 UTC, fenske requested changes
Hey @Safi-Ullah . 👋  Just finished my code review. Please check it out.

2021-06-08 11:28 UTC, fenske commented on pages/organizations/invites/[id].tsx
> +  const {data} = useSWR(user && id ? `/api/organizations/invites/${id}?username=${username}&email=${user.email}&name=${user.name}&photoUrl=${user.photoUrl}` : null, fetcher);
### Bug

If the user doesn't have a name on their GitHub account, this line will send `&name=null` which will end up on Firestore resulting in the following:

![CleanShot 2021-06-08 at 13 17 33](https://user-images.githubusercontent.com/1162212/121175923-edac4000-c85b-11eb-9af0-743660523091.png)

2021-06-08 11:28 UTC, fenske commented on components/TeamMemberManagement.tsx
> +                      inviteTitle = `${person.name}, ${person.username}`
### Bug

Doesn't seem like it works with showing both Name & Username.

![CleanShot 2021-06-08 at 13 23 02](https://user-images.githubusercontent.com/1162212/121176687-cd30b580-c85c-11eb-9003-7fb25922b6af.png)

2021-06-08 18:52 UTC, Safi-Ullah commented on pages/organizations/invites/[id].tsx
> +  const {data} = useSWR(user && id ? `/api/organizations/invites/${id}?username=${username}&email=${user.email}&name=${user.name}&photoUrl=${user.photoUrl}` : null, fetcher);
<img width="586" alt="Screenshot 2021-06-08 at 11 50 11 PM" src="https://user-images.githubusercontent.com/29250597/121240966-52938480-c8b4-11eb-8d45-c9da9fca2e13.png">

I've added the check to not save name/username if they're null/undefined. So, if both of them don't exist then the top row will be empty...

2021-06-08 19:52 UTC, fenske commented on pages/organizations/invites/[id].tsx
> +  const {data} = useSWR(user && id ? `/api/organizations/invites/${id}?username=${username}&email=${user.email}&name=${user.name}&photoUrl=${user.photoUrl}` : null, fetcher);
Strictly speaking there can't be any GitHub user with `undefined` username, right?

Now, the reason we sometimes get `undefined` for username is because of how SWR works. 

If you check in the console it always sends 2 requests on sign in (the first one with `undefined` and the second one with a proper username):

<img width="1719" alt="CleanShot 2021-06-08 at 21 45 49@2x" src="https://user-images.githubusercontent.com/1162212/121248258-8914d380-c8a3-11eb-900f-4d5587a17270.png">

So let's handle it similarly how we do it in `/api/invites/[id].ts`:

![CleanShot 2021-06-08 at 21 51 11@2x](https://user-images.githubusercontent.com/1162212/121248490-cbd6ab80-c8a3-11eb-8d99-dfdf429715ef.png)

2021-06-08 20:54 UTC, fenske commented on pages/organizations/invites/[id].tsx
> +  const {data} = useSWR(user && id ? `/api/organizations/invites/${id}?username=${username}&email=${user.email}&name=${user.name}&photoUrl=${user.photoUrl}` : null, fetcher);
Seems to work properly now. ✔️ 

<img width="573" alt="CleanShot 2021-06-08 at 22 53 53@2x" src="https://user-images.githubusercontent.com/1162212/121256068-75ba3600-c8ac-11eb-9ab5-7119c23b9ef1.png">

2021-06-09 07:19 UTC, merged