Candidate profile
fenske/devskills-app pull request #233
Opened 2021-06-24 21:40 UTC by Safi-Ullah

2021-06-25 05:18 UTC, fenske requested changes
Hi Safi. FYI, I initialized the id's on the preview env. 

I opened it on a 13-inch screen and it rendered really weird. 

Let me share a few comments:

![CleanShot 2021-06-25 at 07 08 15@2x](https://user-images.githubusercontent.com/1162212/123373111-1e42e800-d585-11eb-88b2-5fa1975f4744.png)

I might have missed some more details, but the idea is that the implementation should copy the mockup quite closely.

Let me know if you have any other questions.

2021-06-25 06:22 UTC, Safi-Ullah commented
This is what it was supposed to look like. 

<img width="1440" alt="Screenshot 2021-06-25 at 11 21 03 AM" src="https://user-images.githubusercontent.com/29250597/123379367-70950080-d5a7-11eb-8865-e737a29f1dae.png">

The deployment is looking really weird for me as well. I'll have a look what's causing this.

2021-06-25 06:24 UTC, fenske commented
I see. It could be the "purge" util removing the css classes. 🤔

2021-06-25 06:27 UTC, Safi-Ullah commented
> I see. It could be the "purge" util removing the css classes. 🤔

But shouldn't it only remove unused css classes..?

2021-06-25 06:28 UTC, fenske commented
It should. But I actually experienced problems with purge on a diff repo recently as it was removing too many CSS classes.

In tailwind.config.css, try to update the purge config to this:
```
purge: ['./{components,pages,lib}/**/*.tsx'],
```

2021-06-25 06:32 UTC, fenske commented
Ok, that was it. 👍

Looks better now :) 

<img width="1257" alt="CleanShot 2021-06-25 at 08 32 17@2x" src="https://user-images.githubusercontent.com/1162212/123380553-e0978c80-d58f-11eb-9afc-e8ba29e4a253.png">

2021-06-25 06:35 UTC, Safi-Ullah commented
> Ok, that was it. 👍
> 
> Looks better now :)
> 
> <img alt="CleanShot 2021-06-25 at 08 32 17@2x" width="1257" src="https://user-images.githubusercontent.com/1162212/123380553-e0978c80-d58f-11eb-9afc-e8ba29e4a253.png">

Yeah, I still see 1, 2 issues pointed above...will commit those changes as well....

2021-06-25 06:36 UTC, fenske commented
I'll be off for a bit. Will complete the review by eod. 

In the meantime, could you please update the repo link to how it is on the mockup?

2021-06-25 06:37 UTC, fenske commented
Thanks Safi! Have a good day!

2021-06-25 06:38 UTC, Safi-Ullah commented
> I'll be off for a bit. Will complete the review by eod.
> 
> In the meantime, could you please update the repo link to how it is on the mockup?

Yeah, sure...along with adding space between the slider containers.

2021-06-25 21:24 UTC, fenske approved these changes
@Safi-Ullah I pushed a couple of changes as I was reviewing the code. If you're ok with it, I'm happy to merge this PR.

Great work overall! We'll be further improving this view soon to add the assessment results to it, etc.

2021-06-25 21:24 UTC, fenske commented on components/CandidateInfoPanel.tsx
> +  return (
Mainly highlighted the links + reformated a bit.

2021-06-25 21:24 UTC, fenske commented on components/CandidateOverviewSlideover.tsx
> -import Transition from "./Transition";
Not used anymore, hence deleted.

2021-06-25 21:24 UTC, fenske commented on components/CandidateLablesPanel.tsx
> +export default React.memo(CandidateLabelsPanel);
Btw, nice use of `React.memo`. 👍

2021-06-25 21:24 UTC, fenske commented on components/candidateList/CandidateRow.tsx
> +          <Link href={`/candidates/${challenge.id}`}>
`window.location.href` does a server-side routing whereas `Link` routes client-side. The performance boost is worth it.

2021-06-25 21:27 UTC, fenske commented
Also, one comment about the commit messages. 

For future work, it'd really help if you prepend each commit message with `#  <issue_number>`, e.g. `#229 Implemented a change".

It's handy because it's easy to relate to what issues each commit was associated with when browsing the commit log.

2021-06-26 10:22 UTC, Safi-Ullah commented
> For future work, it'd really help if you prepend each commit message with `# <issue_number>`, e.g. `#229 Implemented a change".

Sure, will do from now on.

2021-06-26 10:26 UTC, Safi-Ullah commented
> @Safi-Ullah I pushed a couple of changes as I was reviewing the code. If you're ok with it, I'm happy to merge this PR.

Yeah, I'm fine with this, you can go ahead and merge the PR.

2021-06-26 20:44 UTC, merged